# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cf2a84a960ec3728ad741f6a86167bece1cef2998258c77084f5907ed0ecf46c73a2ba2e5b70008195c5d2ea16a168a7bf9ff42b7019be7ea2f72b0a8d740a7

test:
  secret_key_base: 43629aa38fb49ff79680b671db6b0d189817a818bce0413c1ff080e567047a517eb388789621cd6462c7025b7347f4b5b3f849bc386f2063ce265cdd66fffdb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
